#!/bin/sh
### BEGIN INIT INFO
# Provides:          musicboxwebserver
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start MusicBox Webserver via zdaemon
### END INIT INFO

#. /etc/rc.d/init.d/functions

#. /etc/sysconfig/network

APP_PATH=/opt/musicbox
PYTHON=/usr/bin/python

start() {
    cd $APP_PATH
    zdaemon -C app.zdconf start
}

stop() {
    cd $APP_PATH
    zdaemon -C app.zdconf stop
}

check_status() {
        cd $APP_PATH
        zdaemon -C app.zdconf status
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        check_status
        ;;
  restart)
        stop
        start
        ;;
  *)
    echo "Usage: /etc/init.d/musicboxwebserver {start|stop|restart|status}"
    exit 1
    ;;
esac
