#!/bin/sh

### BEGIN INIT INFO
# Provides:          musicbox-init
# Required-Start:    $network $remote_fs
# Required-Stop:
# Should-Start:      $named alsa-utils samba
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:    monit
# Short-Description: Initialise musicbox.
### END INIT INFO

NAME="musicbox"
DESC="PiMusicBox"
RUNSCRIPT=/opt/$NAME/startup.sh

USER_CONFIG=/etc/$NAME/$NAME.conf
CURRENT_CONFIG=/opt/$NAME/current.conf
DEFAULT_CONFIG=/opt/$NAME/default.conf

# Gracefully exit if startup script has been removed.
test -x $RUNSCRIPT || exit 0

# Read configuration variable file if present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/lsb/init-functions

. /opt/$NAME/startup.sh

do_start()
{
    pre_init
    init
    post_init
}

do_stop()
{
    true
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC..."
        do_start
        log_end_msg $?
        ;;
    reload|restart|force-reload)
        log_daemon_msg "Reloading $DESC..."
        do_start
        do_stop
        log_end_msg $?
    stop)
        log_daemon_msg "Stopping $DESC..."
        do_stop
        log_end_msg $?
        ;;
    *)
        echo 'Usage: $0 {start|stop|restart|reload|force-reload}'
        exit 1
        ;;
esac

:
