#!/bin/sh
### BEGIN INIT INFO
# Provides:          musicboxwebserver
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Should-Start:      fam
# Should-Stop:       fam
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start MusicBox Webserver via zdaemon
### END INIT INFO

case "$1" in
  start)
    zdaemon -p '/opt/musicbox/musicboxwebserver.py' start
    ;;
  stop)
    zdaemon -p '/opt/musicbox/musicboxwebserver.py' stop
    ;;
  *)
    echo "Usage: /etc/init.d/musicboxwebserver {start|stop}"
    exit 1
    ;;
esac
 
exit 0
