#!/bin/sh
### BEGIN INIT INFO
# Provides:          shairport
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Should-Start:      fam
# Should-Stop:       fam
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Shairport Airplay server.
### END INIT INFO

NAME=`cat /etc/hostname | tr -cd "[:alnum:]"`

case "$1" in
  start)
    /usr/local/bin/shairport -d -a "$NAME (MusicBox)" -w -B "mpc stop" --pidfile /var/run/shairport.pid
    ;;
  stop)
    killall shairport
    ;;
  *)
    echo "Usage: /etc/init.d/shairport {start|stop}"
    exit 1
    ;;
esac
 
exit 0
