#!/bin/sh
### BEGIN INIT INFO
# Provides:          shairportinit
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Shairport Airplay server.
### END INIT INFO

start() {
    NAME=`cat /etc/hostname | tr -cd "[:alnum:]"`
    /usr/local/bin/shairport -d -a "$NAME (MusicBox)" -B "/opt/musicbox/killaudio.sh sp"
}

stop() {
    killall shairport
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        check_status
        ;;
  restart)
        stop
        start
        ;;
  *)
    echo "Usage: /etc/init.d/shairportinit {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
