# Generated by iptables-save v1.4.12 on Fri Jul 12 18:28:53 2013
*filter
:INPUT DROP [1:72]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [15:2194]
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -p tcp -m multiport --dports 22,6600,6680,5900,5901,445,139 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

#avahi
-A INPUT -p udp -m multiport --dport 5353 -j ACCEPT

#samba nameservice
-A INPUT -p udp -m udp --dport 137 -j ACCEPT

#samba share
#-A INPUT -p tcp -m tcp --dport 445 -j ACCEPT
#-A INPUT -p tcp -m tcp --dport 139 -j ACCEPT

#DLNA
-A INPUT -p tcp -m tcp --dport 8200 -j ACCEPT
-A INPUT -p tcp -m udp --dport 1900 -j ACCEPT

COMMIT
# Completed on Fri Jul 12 18:28:53 2013
